// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_5G1Wz8yRVS-Kq46LQyYOVOaRhQnHmrc',
    appId: '1:603320845826:android:edc0433ea50b84f2',
    messagingSenderId: '603320845826',
    projectId: 'inventorio-ee2fe',
    databaseURL: 'https://inventorio-ee2fe.firebaseio.com',
    storageBucket: 'inventorio-ee2fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBTd7U5aoRL-uRezxUIhnE6W62sTARQEA',
    appId: '1:603320845826:ios:edc0433ea50b84f2',
    messagingSenderId: '603320845826',
    projectId: 'inventorio-ee2fe',
    databaseURL: 'https://inventorio-ee2fe.firebaseio.com',
    storageBucket: 'inventorio-ee2fe.appspot.com',
    androidClientId: '603320845826-9mjfjr72j741pj4d38epatmvgg1dt0hr.apps.googleusercontent.com',
    iosClientId: '603320845826-d8k3ofpnl094uf825ngj7bp3e2m550nd.apps.googleusercontent.com',
    iosBundleId: 'com.rcagantas.inventorio',
  );
}
